---
- name: Configure Minecraft Server
  hosts: minecraft_server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Add more tasks for configuration
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar  # Replace with the Minecraft server download URL
        dest: /opt/minecraft/server.jar
        mode: 0644

    - name: Create Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
        daemon_reload: yes
        user: minecraft
        executable: /usr/bin/java
        args: "-Xmx1024M -Xms1024M -jar /opt/minecraft/server.jar nogui"

    # Add more tasks for configuration
